
export const validatorMessage = {
        en: {
            required: 'This field is required.',
            pattern: 'The input value does not match the pattern required.',
            email: 'Invalid email.',
            minLength: 'Minimum length is {0}.',
            maxLength: 'Maximum length is {0}.',
            minNumber: 'Minimal value is {0}.',
            maxNumber: 'Maximal value is {0}.',
            noEmpty: 'Only blank spaces are not allowed.',
            rangeLength: 'The input must be between {0} and {1} symbols long.',
            range: 'The input must be between {0} and {1}.',
            digit: 'The input must be a number.',
            equal: 'The input must be equal to {0}.',
            url: 'The input must be a valid URL.',
            date: 'The input must be a valid date.',
            areEqual: 'The input values in the group must match.',
            passwords: 'Both fields "Password" and "Confirm Password" must match.',
            unknownError: 'Unknown Error.',
        },
        es: {
            required: 'Este campo es requerido.',
            pattern: 'El valor ingreso no es correcto.',
            email: 'Email inválido.',
            minlength: 'El tamaño mínimo es {0}.',
            maxlength: 'El tamaño máximo es {0}.',
            minnumber: 'El valor mínimo es {0}.',
            maxnumber: 'El valor máximo es {0}.',
            noempty: 'Este campo no puede ser vacío.',
            rangelength: 'El valor debe tener entre {0} y {1} caracteres',
            range: 'El valor debe estar entre {0} y {1}.',
            digit: 'El valor debe ser un número.',
            equal: 'El valor debe ser igual a {0}.',
            url: 'El valor debe ser una URL válida.',
            date: 'El valor debe ser una fecha.',
            areequal: 'Los valores del grupo no son iguales.',
            passwords: 'El valor de "Password" y "Confirmar Password" deben ser iguales.',
            unknownerror: 'El valor ingresado no es correcto..', //Error desconocido.
        }
    };